config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'
  resources :coins #Essa linha de código faz o rails gerar 7 rotas padrão para usar com o CRUD desse recurso.

  root to: 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    #Usa o belong_to quando tem uma ID que se relaciona com outra tabela, dessa forma Coins pertence a mining_types
    #Quando coloca essa associação dentro do model, está dizendo ao ActiveRecord que o model Coin vai conversar com o model MiningType
    belongs_to :mining_type # optional: true   ##Determina que o campo é opcional, não precisa ser preenchido na hora que cadastra, dessa forma ele vai cadastrar a moeda e vai deixar vazio o campo mining_type.

end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    #Has_many (tem muitas), realiza a associação inversa, dessa forma o ActiveRecord vai procurar na tabela coins todos os registros com o manyng_type e vai mostrar todos que estão em cada tipo de mineração
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]
        end

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
                I18n.locale = cookies[:locale]
            end
        end
    end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: [:show, :edit, :update, :destroy ] #Essa linha indica que será feito um set da variável coin antes de iniciar o código, somente para as ações declaradas: show, edit, update e destroy. Dessa forma não é preciso declarar uma veriável para ser usada nessas ações. 

  before_action :set_mining_type_options, only: [:new, :create, :edit, :update]

  #No caso do index, como ele não está listado, foi preciso declara a variável dentro da ação.
  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "A moeda foi criada com sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "A moeda foi atualizada com sucesso." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "A moeda foi apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private #Métodos privados só podem ser acessados pelo próprio controller, outros arquivos e outras classes não conseguem acessa eles mesmo que conversem com o controller.

    def set_mining_type_options
      #Variável de sessão
      @set_mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])#Find retorna um único elemento.
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id) #Pega os params passados nos campos de nova moeda, dá um require em coin e permite a descrição, o Acronym e a url_image. Essa estrutura evita que qualquer pessoa envie dados intrusos, que não devem ser tratados pelo controller.
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby on Rails - Jackson Pires [COOKIE]"
    session[:curso] = "Curso de Ruby on Rails - Jackson Pires [SESSION]"
    @nome = params[:nome] 
    #Através da variável global params, pegs o [:nome] que está vindo pela URL e armazena ele dentro da variável de sessão @nome
    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def data_br(data_us)
        data_us.strftime("%d/%m/%y")
    end

    def nome_aplicacao
        "CRYPTO WALLET APP"
    end

    def ambiente_rails
        if Rails.env.development?
            "Desenvolvimento"
        elsif Rails.env.production?
            "Produção"
        else 
            "Teste"
       end
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %> <%# form_with é um helper, que recebe como parâmetro a variável que foi passada em new.html.erb %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Bitcoin" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym, class:"form-label" %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"BTC" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image, class:"form-label" %>
    <%= form.text_field :url_image, class:"form-control", placeholder:"http://img.ur/bitcoin.png" %>
    <%#= image_tag coin.url_image, size: "25x25" %>
  </div>

  
  <div class="col-auto">
    <%= form.label :mining_type_id, class:"form-label" %>
    
    <%# Realiza um select para o formulário do model Coin, passa o nome do campo que será trabalhado (no caso o id do tipo de mineração que está relacionado na tabela Coin), Pega todos os tipos de mineração e faz um collect (que é a mesma coisa que o map, mais ele é mais usado nessa situação pelo fato de tornar mais aparente o fata de que está coletando os dados dos tipos de mineração passados) e por fim, o include_blanck faz aparecer uma opção em branco caso a pessoa não queira preencher o tipo de moeda %>
    <%# Esse select está contrariando a estrutura MVC, pois, no MVC as Views não podem acessar diretamente os models, dessa forma é necessário reestruturar esse código para que a requisição passe pelo controller antes de acessar o model%>
    <%# form.select("mining_type_id", MiningType.all.collect {|m| [m.description, m.id]}, {include_blank: 'Selecione'})%>
    <%= form.select("mining_type_id", MiningType.all.pluck(:description, :id), { include_blank: 'Selecione' }, class:"form-select")  %>
  </div>

  <div class="actions mt-3">
    <%= form.submit nil, class:"btn btn-success btn-sm" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1><%= t('editing') %></h1>

<%= render 'form', coin: @coin %> <%# Renderiza a partial form e passa a variável @coin para dentro dela%>

<%= link_to t('links.show'), @coin, class:"btn btn-dark btn-sm mt-3", role:"button" %>
<%= link_to t('links.back'), coins_path, class:"btn btn-dark btn-sm mt-3", role:"button" %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= Coin.model_name.human(count: @coins.count) %></h2>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @coins.human_attribute_name(:description)%></th>
      <th><%= @coins.human_attribute_name(:acronym)%></th>
      <th><%= @coins.human_attribute_name(:url_image)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <!--<td> <img src= "<%= coin.url_image %>" whidth=25px height=25px/> </td>-->
        <!--<td> <%= image_tag coin.url_image, whidth: 25, height: 25 %></td> -->
        <td> <%= image_tag coin.url_image, size: "25x25" %></td> 
        <td><%= link_to t('links.show'), coin, class:"btn btn-secondary btn-sm", role:"button" %></td> <%# O próprio Ruby identifica a rota e completa com  coin_path para não repetir várias vezes%>
        <td><%= link_to t('links.edit'), edit_coin_path(coin), class:"btn btn-secondary btn-sm", role:"button" %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: t('message.confirm') }, class:"btn btn-danger btn-sm", role:"button" %></td> <%# O próprio Ruby identifica a rota e completa com  coin_path para não repetir várias vezes%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.back'), welcome_index_path, class:"btn btn-dark btn-sm", role:"button" %>
<%= link_to t('new.coin'), new_coin_path, class:"btn btn-dark btn-sm", role:"button" %>

app/views/coins/new.html.erb
<h1><%= t('new.coin') %></h1>

<%= render 'form', coin: @coin %> <%# Renderiza a partial form e passa a variável @coin para dentro dela%>

<%= link_to t('links.back'), coins_path, class:"btn btn-dark btn-sm mt-3", role:"button" %>

app/views/coins/show.html.erb
<h1><%= t('showing.coin') %></h1>
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:description), class:"form-label" %>
    <%= text_field_tag  nil, @coin.description, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:acronym), class:"form-label" %>
    <%= text_field_tag nil, @coin.acronym, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:url_image), class:"form-label" %>
    <%= text_field_tag nil, @coin.url_image, class:"form-control", disabled: true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:mining_type), class:"form-label" %>
    <%= text_field_tag nil, @coin.mining_type.description, class:"form-control", disabled: true %>
  </div>
</form>

<%= link_to t('links.edit'), edit_coin_path(@coin), class:"btn btn-dark btn-sm mt-3", role:"button" %>
<%= link_to t('links.back'), coins_path, class:"btn btn-dark btn-sm mt-3", role:"button" %>

app/views/layouts/application.html.erb
<!--Template para toda a aplicação-->
<!DOCTYPE html>
<html>

<head>
  <title>CryptoWallet</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container-fluid">
    <ul class="nav justify-content-end">
      <li>
      <%= link_to 'HOME', root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Português (BR)', root_path(locale: 'pt-BR'), class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'English', root_path(locale: 'en'), class:"nav-link"%>
      </li>
    </ul>
    <%= yield %>
  </div>
</body>

</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Proof of Work" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym, class:"form-label" %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"PoW" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit nil, class:"btn btn-success btn-sm"%>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1><%= t('editing') %></h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.show'), @mining_type, class:"btn btn-dark btn-sm mt-3", role:"button" %>
<%= link_to t('links.back'), mining_types_path, class:"btn btn-dark btn-sm mt-3", role:"button" %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th><%= @mining_types.human_attribute_name(:description)%></th>
      <th><%= @mining_types.human_attribute_name(:acronym)%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type, class:"btn btn-secondary btn-sm", role:"button" %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type), class:"btn btn-secondary btn-sm", role:"button" %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('message.confirm') }, class:"btn btn-danger btn-sm", role:"button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.back'), welcome_index_path, class:"btn btn-dark btn-sm", role:"button" %>
<%= link_to t('new.mining_type'), new_mining_type_path, class:"btn btn-dark btn-sm", role:"button" %>

app/views/mining_types/new.html.erb
<h1><%= t('new.mining_type') %></h1>

<%= render 'form', mining_type: @mining_type%>

<%= link_to t('links.back'), mining_types_path, class:"btn btn-dark btn-sm mt-3", role:"button" %>

app/views/mining_types/show.html.erb
<h1><%= t('showing.mining_type') %></h1>
<p id="notice"><%= notice %></p>

<form>
  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:description), class:"form-label" %>
    <%= text_field_tag  nil, @mining_type.description, class:"form-control", disabled:true %>
  </div>

  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:acronym), class:"form-label" %>
    <%= text_field_tag nil, @mining_type.acronym, class:"form-control", disabled: true %>
  </div>
</form>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type), class:"btn btn-dark btn-sm mt-3", role:"button" %>
<%= link_to t('links.back'), mining_types_path, class:"btn btn-dark btn-sm mt-3", role:"button" %>

app/views/welcome/_menu.html.erb
<%= link_to "#{Coin.model_name.human}", coins_path, class:"btn btn-dark btn-lg", role:"button" %>
<%= link_to "#{MiningType.model_name.human}", mining_types_path, class:"btn btn-dark btn-lg", role:"button" %>

app/views/welcome/index.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-5 fw-bold"><%= t('welcome') %></h1>
    <p class="col-md-8 fs-4"><%= t('messages.welcome') %></p>
    <hr class-"my-4">
    <p><%= t('messages.menu') %></p>
    <%= render "menu" %> <!--Renderiza a partial menu-->
</div>